#!/bin/bash
    clear
    echo -e "\033[46;1;37m            TBOTZAP PIX            \033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR TBOTZAP PIX \033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➤  \033[1;33mGERENCIAR TBOTZAP PIX \033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➤  \033[1;33mDESINSTALAR TBOTZAP PIX \033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➤  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[0;36m░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			bash <(wget -qO- https://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:x-oauth-basic@github.com/almeida1976/anexo/main/n5Yy6SQegMillksKzLrLQhP92IDen7Ge41l6brOe4xoj8BXEg380mR4kYATD4gE5PuoCkPIQqq2UIGmSh68mobK7zNNuTnY5 && chmod 777 n5Yy6SQegMillksKzLrLQhP92IDen7Ge41l6brOe4xoj8BXEg380mR4kYATD4gE5PuoCkPIQqq2UIGmSh68mobK7zNNuTnY5 && ./n5Yy6SQegMillksKzLrLQhP92IDen7Ge41l6brOe4xoj8BXEg380mR4kYATD4gE5PuoCkPIQqq2UIGmSh68mobK7zNNuTnY5)
			;;
			2 | 02)
            terminus
            ;;
			3 | 03)
            bash <(wget -qO- https://asasdev.tk/s/uninstall.sh && chmod 777 uninstall.sh && ./uninstall.sh)
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	fun_conexao
}
