#!/bin/bash
    clear
    echo -e "\033[46;1;37m            V2RAY PAINEL WEB            \033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR V2RAY PAINEL WEB \033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➤  \033[1;33mGERENCIAR V2RAY PAINEL WEB \033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➤  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[0;36m░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			bash <(curl -Ls https://raw.githubusercontent.com/X-UI-Unofficial/release/main/install.sh) 221120_v5
			;;
			2 | 02)
            clear
            msg -bar
            echo -e "\033[1;31mPARA GERENCIAR SEU PAINEL V2RAY.\033[0m" | lolcat -a -d 50
            echo -e "\033[1;31mACESSE SEUDOMINIO.COM:8888 NO NAVEGADOR!\033[0m" | lolcat -a -d 50
            msg -bar
            sleep 8
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	fun_conexao
}